"""
Base classes for all classifiers.

Provides a common interface for every classifier used in the
Signal Triage Pipeline.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Dict, Any, Optional



@dataclass
class Prediction:
    """
    Represents the prediction generated by a classifier.
    """

    label: str

    confidence: float

    classifier_name: str

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )

    score: Optional[float] = None



class BaseClassifier(ABC):
    """
    Abstract base class for all classifiers.

    Every classifier must implement predict().
    """

    @abstractmethod
    def predict(
        self,
        text: str
    ) -> Prediction:
        """
        Predict category for input text.

        Parameters
        ----------
        text : str
            Input signal text.

        Returns
        -------
        Prediction
            Prediction object containing:
            - label
            - confidence
            - classifier name
            - metadata
        """

        raise NotImplementedError(
            "Subclasses must implement predict()."
        )